language: python
python:
  - "2.7"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - nose2 --with-coverage --coverage structurebot
branches:
  only:
    - master
    - develop
    - /^release/.*/
after_success:
  - coveralls